application: cloudywebproject
version: 1
runtime: python27
api_version: 1
threadsafe: false 

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js
- url: /.*
  script: cloudywebproject.app

inbound_services:
- warmup

libraries:
- name: jinja2
  version: latest
- name: pycrypto
  version: "2.6" 
