application: cloudywebproject
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: cloudywebproject.app

inbound_services:
- warmup

libraries:
- name: jinja2
  version: latest
